### ISSUE TITLE
Running Jar files 

### ISSUE THREAD

**Issue by anuagg** [worldofbalance/wob-server#11]
As I mentioned in my comment under PR #4, I wasn't able to run the minigame servers through our current code. But when I tried the method that was used by the previous batch, i.e. They had seperate folders containing conf and dist for each mini server. They accessed miniGame Jar files through dist ( eg: "../Speed_Server/dist/Speed_Server.jar"). This somehow maintained the integrity of each server I guess, coz each server had their individual configuration files and libraries. 

I would recommend that we follow this method in our current code. [ refer to the pic attached]
![image](https://cloud.githubusercontent.com/assets/14930862/14230955/c51d3958-f923-11e5-8f7c-580365a975c5.png)

Also, am getting this error, whenever a new client connects with the code (after Logging in)
![image](https://cloud.githubusercontent.com/assets/14930862/14230556/437ba364-f912-11e5-89e1-8cde342c3e31.png)

Have added dev-sdv-minigame branch with the updated code. Please let me know if the changes made are apt or needs to be reconsidered. 

(Again, this might be a windows/netbeans issue if its running fine on intelliJ)

**Comment by jensvdh** [comment]
Is there a reason to have a /lib folder there?

Don't the libraries into the target JAR when you compile the SeaDivided JAR file?

**Comment by anuagg** [comment]
Yes I guess there is. The code does not seem to work otherwise. I think the reason is mentioned here: dev-sdv-minigame/mini_game_server_jar/Speed_Server/dist/README.TXT.  
It says:
"When you build an Java application project that has a main class, the IDE
automatically copies all of the JAR
files on the projects classpath to your projects dist/lib folder. The IDE
also adds each of the JAR files to the Class-Path element in the application
JAR files manifest file (MANIFEST.MF)."
Thus probably, we need access to those exact jar files that IDE had copied while building that java application. (Am not sure if this reason is correct. But I surely know that having these jar files attached is a necessity )
I've added lib folder for all three servers. Basically have copy pasted the minigame server folders that we had previous to our current version. 

(Check. Have updated the image in my previous comment)

**Comment by niculistana** [comment]
@anuagg Here are the following steps I did to run Running Rhino server locally without errors:
1.) Run server from netbeans (`dev-rr-before-merge` branch)
2.) Run client from Unity (`developement` branch)
3.) Run Game.unity scene from the client
4.) Login using `bobby` as the username and `123456` as the password. (Make sure the NetworkManager.cs script is toggled to turn on).
5.) Create a running rhino room by using Multiplayer Games>Running Rhino
6.) The client should have the following log:

Here is my log from the client:

> Sent Request No. 161 [GetRoomsProtocol]
> UnityEngine.Debug:Log(Object)
> NetworkManager:Update() (at Assets/Scripts/Network/NetworkManager.cs:52)

Here is my log for the server:

> World of Balance Server v1.00 is starting...
> Loading Configuration File...Done!
> Loading Species...1.15E-5
> 0.04
> 0.0075
> Done!
> Loading Requests...Done!
> Loading Experience Table...Done!
> Loading Worlds...Done!
> All mini games initialized: 2/2 avaiable
> Running server: Running_Rhino:
> Jar: ./mini_game_server_jar/Speed_Server.jar
> Running server: Card_of_Wild:
> Jar: ./mini_game_server_jar/Cards_Server.jar
> Now accepting connections...
> [Card_of_Wild:] Cards of the Wild Server v1.00 is starting...
> [Running_Rhino:] World of Balance Server v1.00 is starting...
> [Running_Rhino:] 
> [Card_of_Wild:] > Loading Configuration File...Done!
> 127.0.0.1 is connecting...
> User 'bobby' is connecting...
> User 'bobby' has successfully logged in.
> The client is requesting for quiting...
> New room created with ID: 101
> Number of rooms: 1

**Comment by anuagg** [comment]
@niculistana  I too had the code running till this point. But all this is handled by lobby server and not minigame server. Minigame servers were actually not working. You'll get an output as - 
![image](https://cloud.githubusercontent.com/assets/14930862/14236227/daecf93c-f9c6-11e5-9e66-552e9a4858a8.png)
when the minigame servers run to a point where they can accept client connection (highlighted line) As you might notice that in your server log,  the running rhino server is only executed to a point where only [Running_Rhino:] World of Balance Server v1.00 is starting... is displayed.

**Comment by anuagg** [comment]
Also, to run the given client code locally, we need to make changes in the config file in unity. We have to un-comment the localhost code line.
![image](https://cloud.githubusercontent.com/assets/14930862/14236362/fd099334-f9c8-11e5-825a-70ebdd9d765a.png)

Else, the client code won't be locally communicating with our local server code.

**Comment by anuagg** [comment]
And for the error I've mentioned in my previous comment, its an error that gets displayed on the console   now and then when network communication is being made between client and server. But this error is not interfering with the communication. I am able to connect to a GameRoom and play games ( with some glitches ).

**Comment by niculistana** [comment]
@anuagg Would you be able to meet sometime after class on Tuesday to talk more about your issue? Thanks.

**Comment by anuagg** [comment]
@niculistana Sure! We can even discuss this during our class timings on Tuesday. I think professor Yoon has some work and is busy that day. So we'll not be having regular class. I can also meet after class though.

**Comment by niculistana** [comment]
@anuagg Sounds good, I am also stuck to where I can create rooms but cannot actually run the game with two clients.

I tried connecting to a server running in my other computer in the same network by changing the `REMOTE_HOST` to the other computer's IP address. I am getting the following error: 

`Socket error: System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP, Boolean requireSocketPolicy) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remote_end_point) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPAddress[] ipAddresses, Int32 port) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:Log(Object)
RR.RRConnectionManager:SetupSocket() (at Assets/RRAssets/Network/RRConnectionManager.cs:57)
RR.RRConnectionManager:Start() (at Assets/RRAssets/Network/RRConnectionManager.cs:35)`

**Comment by anuagg** [comment]
@niculistana Did you check dev-sdv-minigame branch? I got it working by attaching conf and jar files with each minigame. This method was used by the batch previous to us, I guess. 
Also, you need to change port numbers on Constants scripts (specific to each minigame) on client side unity code to get the games started.

**Comment by GilBu** [comment]
Ivan and I Fixed the error whenever a new client connects with the code. It was just a bunch of misnamed paths in some files in the atn folder from "src\atn\SimJobsConfig.properties" to "src\shared\atn\SimJobsConfig.properties" (changes have been pushed).

**Comment by anuagg** [comment]
@GilBu Awesome
