### ISSUE TITLE
Sea divided server cannot connect

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/wob-server#15]
I got a fresh copy of the `development` branch and I tried running the server. For some reason, the sea divided server gets stuck at: Sea Divided v1.00 is starting...

Any help would be appreciated!

**Comment by anuagg** [comment]
@niculistana last time I checked it was working fine for me. The reason might be that the port is already in use.  For example now when we run and close our wob server on local machine, main lobby server port gets close eventually with the project. But the ports we've opened through jar file remain open. I.e. Port/socket still in listening state. We have to close those ports manually when closing server program. You can do this using command prompt or tcpview software. 
Check and try this. If problem still persists, let me know. 
Thanks for bringing up the issue though.

**Comment by niculistana** [comment]
@anuagg You are correct. I am using this stackoverflow issue to find and kill processes that use the port: http://stackoverflow.com/a/18706913/1894421

I tried killing the process that uses 20040 (Sea Divided port) but it keeps restarting a new process when I try to kill it. Thank you for the help!

**Comment by rujoota** [comment]
Have you tried running both servers simultaneously in netbeans? I just tried commenting out loading of my jar file in Minigame.java & ran it in parallel with wob-server.

**Comment by niculistana** [comment]
@rujoota I tried running the jar file by itself using `java -jar`, it looks like it runs normally.

**Comment by ilmiyoon** [comment]
I guess things are well taken care for this one.
