### ISSUE TITLE
LBY - Minigame jar server processes not logging stderr

### ISSUE THREAD

**Issue by rupalkhilari** [worldofbalance/wob-server#20]
Hi, 

It seems like the minigame servers are only logging stdout from the processes run using 'java -jar', and not the standard error. As a result any errors thrown from the minigame servers are not showing up while running from the lobby unless they are written out to stdout. 

Is it ok to display a combined log of stdout and stderr for each process so it would make it easier to debug ? I have committed a small change [here](https://github.com/worldofbalance/wob-server/blob/dev-sdv-log-minigame-err/src/lby/MiniGame.java#L90) (to the dev-sdv-log-minigame-err  branch) which allows this and seems to be working as expected.

Please let me know if there are concerns regarding this. If not, I can create a PR for it.

Thanks.

**Comment by Fito** [comment]
@rupalkhilari Good catch. Make a PR and let's get it merged.

**Comment by rupalkhilari** [comment]
Sure, have raised PR https://github.com/worldofbalance/wob-server/pull/22 
Thanks.

**Comment by rupalkhilari** [comment]
Thanks @anuagg for merging this.
