### ISSUE TITLE
[Multiplayer Games] Conf file abolute path not resolving to the correct conf.

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/wob-server#27]
For anyone working on multiplayer games, gas anyone actually deployed a newer jar file than the ones contained under mini_game_server_jar?

It looks like when building a jar file, the gameServer.conf always resolves to the lobby's port number: 9255.

I tried tracing the code and it turns out that the path to get each mini game's conf file does not resolve 

Under `{minigame}/core/GameServer.java`:

```
 `public final void configure() {

    String serverConf = "conf/gameServer.conf";
    File f = new File(serverConf);

    if (!f.exists()) {
        // get current absolute path
        CodeSource codeSource = GameServer.class.getProtectionDomain().getCodeSource();
        File jarFile;
        try {
            jarFile = new File(codeSource.getLocation().toURI().getPath());
            serverConf = jarFile.getParentFile().getPath() + "/../conf/gameServer.conf";
        } catch (URISyntaxException ex) {
            Logger.getLogger(GameServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    configuration = new GameServerConf();
    configuration.setConfRecords(new ConfFileParser(serverConf).parse());
}`
```

The code above shows that the path should be under `conf/gameServer.conf`, otherwise, it would be on `{codeSource_path} + /../conf/gameServer.conf`.

Has anyone else noticed this? @worldofbalance/server 

Cheers,
Nicu

**Comment by rujoota** [comment]
Yes, for COW we use following code in our game server class and it recognizes correct conf file.

```
 CodeSource codeSource = cow.core.GameServer.class.getProtectionDomain().getCodeSource();
            File jarFile = new File(codeSource.getLocation().toURI().getPath());
            String separator = System.getProperty("file.separator");
            String serverConf = jarFile.getParentFile().getPath() + separator + ".."+separator+"conf" + separator + "gameServer.conf";
            System.out.println("config file path:"+serverConf);
            File f = new File(serverConf);
            if (!f.exists()) {
                // get current absolute path
                System.out.println("Error loading config file for COW");
                serverConf = jarFile.getParentFile().getPath() + separator +"conf" + separator + "gameServer.conf";
            }
```

**Comment by niculistana** [comment]
Thank you @rujoota! @laisture @jkrubin Can you please implement and test this on `dev-rr` branch? You can do so by setting rr.core.GameServer as the main file when you hit the play button on netbeans. It should be returning a port value that is the same as our `gameServer.conf` file's value, not the lobby server's `gameServer.conf`.

**Comment by laisture** [comment]
@niculistana I'm on it
