### ISSUE TITLE
Jar file cannot resolve dependency

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/wob-server#3]
Hello guys, I uploaded a jar file under ddeb4ca it looks like the builder cannot find the ObjectPool class. I have checked the .jar file's Manifest for the Speed_Server and it looks like this:

Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.4
Created-By: 1.8.0_65-b17 (Oracle Corporation)
Class-Path: lib/activation.jar lib/axis.jar lib/commons-dbcp-1.4.jar l
 ib/commons-discovery-0.5.jar lib/commons-logging-1.1.1.jar **lib/common
 s-pool-1.6.jar** lib/gson-2.2.2.jar lib/javax.wsdl_1.6.2.v201012040545.
 jar lib/jaxrpc.jar lib/json_simple-1.1.jar lib/mail.jar lib/mysql-con
 nector-java-5.1.22-bin.jar lib/saaj.jar
X-COMMENT: Main-Class will be added automatically by build
Main-Class: core.GameServer

Clearly, the ObjectPool class is there, but for some reason the builder cannot find it. If anyone could help that would be great.

*\* Now, looking at the build's README for the wob-server's `/dist` folder, it says that:

> If a library on the projects classpath also has a Class-Path element
> specified in the manifest,the content of the Class-Path element has to be on
> the projects runtime path.

I checked the runtime path and it does include **lib/common
 s-pool-1.6.jar** in `WoB_Server`...

**Comment by niculistana** [comment]
@hunvil who did the builds last year?

**Comment by jan-burianek** [comment]
The truth is that Apache project commons pool v1.6 is really outdated https://commons.apache.org/proper/commons-pool/ since the current version bears number 2.4.2. Although the version 1.6 is the last stable version from the 1. version branch, maybe it is not able to interact with the other dependencies.

**Comment by jensvdh** [comment]
![image](https://cloud.githubusercontent.com/assets/2640481/14124893/fda72352-f5bc-11e5-8dbb-741f91e20759.png)

I'm guessing this issue relates to this bug?

**Comment by jensvdh** [comment]
@worldofbalance/running-rhino any ideas?

**Comment by haichuand** [comment]
It seems like the problem was caused by repeat thread start code in MiniGame.java, line 92~101. After deleting the extra code (and the unnecessary brackets) the problem was solved for me.

**Comment by jensvdh** [comment]
Cool. Want to create a pull request with this fix?

**Comment by haichuand** [comment]
Sure. Which branch should I create the pull request?

**Comment by niculistana** [comment]
Thank you @haichuand! You can pull the https://github.com/worldofbalance/wob-server/tree/dev-rr-before-merge branch and make a commit from there. It is already on a pull request which @jensvdh is moderating.

**Comment by haichuand** [comment]
Just created the pull request

**Comment by jensvdh** [comment]
Is it  #5 ?

**Comment by niculistana** [comment]
@jensvdh No it is not, he created a pull request for #4 which I reviewed and merged. You can see the commit under here: eed38e2080e9805d994383d9e07952b9aef20db7
