### ISSUE TITLE
thecity.sfsu.edu refusing connections to ports above 9999

### ISSUE THREAD

**Issue by rupalkhilari** [worldofbalance/wob-server#31]
I have been unable to get the client to connect to servers running on thecity with 5 digit port numbers since yesterday. It seems that thecity.sfsu.edu is now refusing client connections to ports above 9999. We have our minigame servers running on ports 20040, 20039, etc which don't seem to be accepting connections now. I have tried verifying this with telnet and [PortQry](https://www.microsoft.com/en-us/download/details.aspx?id=17148). Although the port appears as LISTENING in netstat it refuses a connection. 

However the client is able to connect to the server when run on a port such as 9258 on thecity.sfsu.edu.
Any other minigames noticed this in the past day or so ? Perhaps something has changed on thecity causing these ports to be filtered.

**Comment by jensvdh** [comment]
Maybe firewall settings? Seems odd.

We are using port 16567 and it is not causing issues for now.

**Comment by rupalkhilari** [comment]
Thats possible. Was your client able to connect to thecity.sfsu.edu on port 16567 ? telnet and netcat do not seem to be connecting to that port from my machine on thecity . Although I am able to access this port on another external server. 
Rujoota also seemed to face the same issue in https://github.com/worldofbalance/wob-server/issues/32 . 
We could close this though since we are using different port numbers as a workaround.

**Comment by rupalkhilari** [comment]
It perhaps is dependent on the SFSU WLan connection and the their firewall. I am not able to access it from outside the SFSU wifi connection but haven't tried this test while on campus. Perhaps these ports are filtered by thecity firewall only for connections outside the SFSU wifi.

**Comment by rupalkhilari** [comment]
Yes, I confirmed that these same ports 20040, 20049 etc and those above 9999 are working while  connecting from within the SFSU Wlan. Though they are not accessible from outside of it, so it is perhaps the firewall on thecity is preventing connection to these ports from an external connection (I was earlier trying this at home). I believe we just need to make sure we start the servers on ports that are accessible from everywhere (9258, 9260 etc). I can close this for now.
