### ISSUE TITLE
Deploying server jar to thecity

### ISSUE THREAD

**Issue by rujoota** [worldofbalance/wob-server#32]
Hi all,

I am trying to deploy server to thecity. I tried connecting to thecity using this command(same can be done by filezilla)

scp -r  /local_path_to_Woc_Server/ rshah1@thecity.sfsu.edu:/home/student/rshah1/COWServer

I got the file uploaded, but when I am trying to run it with java -jar command, its giving me exception
`Exception in thread "main" java.lang.UnsupportedClassVersionError: cow/core/GameServer : Unsupported major.minor version 52.0
`

Now I googled about it and found that its because of version mismatch. When I checked, the server had java 1.6 and our code works on 1.8. Now I don't know how to change the version. Can someone help me here?

**Comment by anuagg** [comment]
to run the jar file for java1.8 we have to write /opt/java8/bin/java -jar jarname.jar  command after going to the directory where the jar file is. Did you try running it through this command and path ? @rujoota

**Comment by jensvdh** [comment]
You can also add the opt/java8/bin/ path to your PATH in ~./bashprofile

**Comment by rujoota** [comment]
Hi @anuagg...I am now able to run it but when I specify thecity.sfsu.edu as host name, unity is not able to connect to it.

**Comment by anuagg** [comment]
@rujoota  which port are you running your server on ? Check issue #31 try any port that is under 9999 ( except 9255,9257 and 9258 ) and see if it works.

**Comment by rujoota** [comment]
Yupp, I guess that was the issue. I am now using 9260 for COW port. Thanks.
