### ISSUE TITLE
The database we are using is outdated.

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/wob-server#9]
I logged in our current Running Rhino database in this repo using the following credentials:
## Database URL

DBURL thecity.sfsu.edu
## Database name

DBName csc63101
## Database user name

DBUsername csc63101
## Database user password

DBPassword csc631_01

The following query does not work because the `hidden` column does not exist under the `species` or `species_id` tables:
## The current query to get plants:

 `String query = ""
                + "SELECT * "
                + "FROM`species`s JOIN`species_nodes`sn ON s.`species_id`= sn.`species_id`"
                + "WHERE`organism_type`= 1 AND`hidden`= 0 "
                + "ORDER BY s.`species_id`, sn.`node_id`";`
### Current columns:

```
                `plantType = new PlantType(species_id);
                plantType.setName(rs.getString("name"));
                plantType.setOrganismType(rs.getInt("organism_type"));
                plantType.setCost(rs.getInt("cost"));
                plantType.setDescription(rs.getString("description"));
                plantType.setCategory(rs.getString("category"));
                plantType.setAvgBiomass(rs.getInt("max_biomass"));
                plantType.setWaterNeedFrequency(rs.getInt("water_need_frequency"));
                plantType.setLightNeedFrequency(rs.getInt("light_need_frequency"));
                plantType.setGrowRadius(rs.getFloat("grow_radius"));
                plantType.setCarryingCapacity(rs.getFloat("carrying_capacity"));
                plantType.setTrophicLevel(rs.getFloat("trophic_level"));
                plantType.setGrowthRate(rs.getFloat("growth_rate"));
                plantType.setModelID(rs.getInt("model_id"));
                plantType.setHealChance(rs.getFloat("heal_chance"));
                plantType.setGroupCapacity(rs.getInt("group_capacity"));`
```
### Columns in `species` and `speciesId` under `thecity.sfsu.edu`:

`species_id, name, organism_type, cost, description, category, biomass, diet_type, carrying_capacity, metabolism, trophic_level, growth_rate, model_id, unlock, species_id, node_id, distribution`
## Missing columns:

`hidden, max_biomass, water_need_frequency, light_need_frequency, group_capacity`
## Update:

I switched the `db.conf` file to:
## Database URL

DBURL smurf.sfsu.edu    
## Database name

DBName deBuggerWeb
## Database user name

DBUsername deBuggerWeb
## Database user password

DBPassword deBugger

And I was able to retrieve data. So if Yoon is alright with migrating data from smurf to thecity, I will go ahead and do that.

**Comment by niculistana** [comment]
@brianxautumn Please see this issue about not being able to get SpeciesTable for the client.

**Comment by niculistana** [comment]
@worldofbalance/database Please take a look at this issue, and coordinate with @ilmiyoon to see if we should update thecity's database.

**Comment by niculistana** [comment]
Gary, our TA said that 

> If code being utilized requires it to function, then yes.

over here: https://ilearn.sfsu.edu/ay1516/mod/forum/discuss.php?d=142722&parent=329735

So it looks like we need to update the schema for some tables in our thecity.sfsu.edu to reflect smurf.sfsu.edu's database tables.

**Comment by jensvdh** [comment]
Do you have access to the databases?

Also tagging the database team so everyone is aware.
@worldofbalance/database

**Comment by brianxautumn** [comment]
Hey guys need help on database? Im from Don't Eat Me but we need the species table running too.

**Comment by kbigleybodlak** [comment]
hey there, I'm wondering what would be a good way to connect to and view the databases, both on thecity and at the smurf. I've been trying to use MySQL workbench and that's getting errors, I've used putty to get on  thecity server, but still a little confused about  how to effectively view the databases.  I'm on new game team and mostly been working out what information our game will use, which is in progress as we build basic game elements, so I haven't looked into these databases as of yet. 
my email: hypnothistle@yahoo.com
I'm going to keep trying to find a way to view these databases in the meantime.

**Comment by jensvdh** [comment]
What MySQL workbench errors are you getting? I'm not sure if the ports are opened towards the outside world. Not even sure if that's a good idea, for security reasons.

We can potentially install PhPmyAdmin on the servers and expose that on port 80, but I'm not sure if I have enough rights on thecity to do that.

You can also install the databases on localhost by importing the SQL files. This is probably a safer way to develop.

**Comment by kbigleybodlak** [comment]
using workbench 6.3.6 community version using port 3306 to connect to thecity.sfsu.edu and the credentials from the credentials list, the workbench gives the error: "malformed packet" 
a phpmyadmin would be a nice idea, I have had experience in 413 and 648 with using it, but not setting one up yet.
I will try importing them to see how they look, thanks.

**Comment by jensvdh** [comment]
Did you connect over a secure connection?

https://bugs.mysql.com/bug.php?id=78947

**Comment by kbigleybodlak** [comment]
I did not attempt connect using ssh, which I think may be an issue, but looking at the credentials file on ilearn, I wasn't sure which credentials to use for the ssh username and password.

**Comment by jensvdh** [comment]
Try using localhost first. I'll investigate into getting PhpMyAdmin or similar up- and running.

**Comment by haichuand** [comment]
I'm using PhpMyAdmin website for viewing databases on smurf and thecity. It seems to be working fine:
http://smurf.sfsu.edu/phpmyadmin/
http://thecity.sfsu.edu/phpmyadmin/
So which database should we use as first choice?

**Comment by niculistana** [comment]
Yes, I also used smurf like @haichuan did. And it was working fine with me.
Should we start changing the schema for thecity.sfsu.edu and migrate records?

On Wed, Mar 30, 2016 at 11:03 PM, haichuand notifications@github.com
wrote:

> I'm using PhpMyAdmin website for viewing databases on smurf and thecity.
> It seems to be working fine:
> http://smurf.sfsu.edu/phpmyadmin/
> http://thecity.sfsu.edu/phpmyadmin/
> So which database should we use as first choice?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/worldofbalance/wob-server/issues/9#issuecomment-203769627

## 

Nicu Listana
_LinkedIn
http://www.linkedin.com/profile/view?id=134425825&locale=en_US&trk=tab_pro.Twitter
https://twitter.com/#!/apebeast.G+
https://plus.google.com/b/101191476444716618590/101191476444716618590/_

**Comment by kbigleybodlak** [comment]
update: I'm looking at the databases through phpmyadmin now.  I think changing thecity to migrate over the records from the smurf would be best, considering that the schema for the db at thecity.sfsu.edu is already using many elements in the smurf db.  
However, I also noticed that in last year's documentation, they were using thecity as the server for the main database, so does this mean they were using smurf's database as a testing area?
why are there two databases to hold the same information? (Is one a backup? optimization?) 
if there is some documentation about it, that would be helpful.

**Comment by ilmiyoon** [comment]
Thanks a lot everyone! Thecity was used for the development and smurf was used for deployment. However, last year, thecity was the only one that students used to support for their mini games. So, smurf must be out-dated. Once we get thecity DB finalized and tested, then we can migrate to smurf at the time.

**Comment by ilmiyoon** [comment]
So, Yes! please migrate from smurf to thecity.

**Comment by niculistana** [comment]
@worldofbalance/database Please add this to your milestone for each specific game you are working on, migrate the database from smurf.sfsu.edu to thecity.sfsu.edu, and make sure to properly test the DAO.

**Comment by jensvdh** [comment]
Yes. We will be using thecity.sfsu.edu until the end of the semester. Then if we have time, we will be using smurf.sfsu.edu, which is supposed to be our "production" environment.

So please make sure thecity is running all the latest and greatest database files so we can point our clients to it.

**Comment by haichuand** [comment]
I imported the 'simtest_node_params' table from smurf to thecity; added 'atn_manipulation_id' column in ecosystem table; added 'csv_atn' column in sim_job table to fix some of the SQL exceptions when running server.

**Comment by jensvdh** [comment]
We had a database discussion last week. Can we close this issue?

**Comment by niculistana** [comment]
@worldofbalance/database please update us on the DB changes. Who is taking care of this issue?

**Comment by ilmiyoon** [comment]
@niculistana Haichuan already took care of the issue and explained in this issue. Do you need more information than what Haichuan commented 6 days ago?

**Comment by niculistana** [comment]
@ilmiyoon I am now all caught up! I will close the issue now.
